export enum CgaColors {
  Black = "black",
  Red = "red",
  Green = "green",
  Blue = "blue",
  Yellow = "yellow",
  Cyan = "cyan",
  Magenta = "magenta",
  Orange = "orange",
  Chartreuse = "chartreuse",
  SpringGreen = "springGreen",
  Azure = "azure",
  Violet = "violet",
  Rose = "rose",
  LightGray = "lightGray",

  DarkGray = "darkGray",
  LightRed = "lightRed",
  LightGreen = "lightGreen",
  LightBlue = "lightBlue",
  LightYellow = "lightYellow",
  LightCyan = "lightCyan",
  LightMagenta = "lightMagenta",
  LightOrange = "lightOrange",
  LightChartreuse = "lightChartreuse",
  LightSpringGreen = "lightSpringGreen",
  LightAzure = "lightAzure",
  LightViolet = "lightViolet",
  LightRose = "lightRose",
  White = "white",
}
