/**
 * All standard `KeyboardEvent.code` strings (UI-Events spec § 2.3).
 * See <https://w3.org/TR/uievents-code/>.
 */
export type KeyCode =
  /* ————————————————— Alphanumeric ————————————————— */
  | "KeyA"
  | "KeyB"
  | "KeyC"
  | "KeyD"
  | "KeyE"
  | "KeyF"
  | "KeyG"
  | "KeyH"
  | "KeyI"
  | "KeyJ"
  | "KeyK"
  | "KeyL"
  | "KeyM"
  | "KeyN"
  | "KeyO"
  | "KeyP"
  | "KeyQ"
  | "KeyR"
  | "KeyS"
  | "KeyT"
  | "KeyU"
  | "KeyV"
  | "KeyW"
  | "KeyX"
  | "KeyY"
  | "KeyZ"
  | "Digit0"
  | "Digit1"
  | "Digit2"
  | "Digit3"
  | "Digit4"
  | "Digit5"
  | "Digit6"
  | "Digit7"
  | "Digit8"
  | "Digit9"

  /* ————————————————— Function keys ————————————————— */
  | "F1"
  | "F2"
  | "F3"
  | "F4"
  | "F5"
  | "F6"
  | "F7"
  | "F8"
  | "F9"
  | "F10"
  | "F11"
  | "F12"
  | "F13"
  | "F14"
  | "F15"
  | "F16"
  | "F17"
  | "F18"
  | "F19"
  | "F20"
  | "F21"
  | "F22"
  | "F23"
  | "F24"

  /* ————————————————— Control / navigation ————————————————— */
  | "Backspace"
  | "Tab"
  | "Enter"
  | "Escape"
  | "CapsLock"
  | "ShiftLeft"
  | "ShiftRight"
  | "ControlLeft"
  | "ControlRight"
  | "AltLeft"
  | "AltRight"
  | "MetaLeft"
  | "MetaRight"
  | "ContextMenu"
  | "Pause"
  | "PrintScreen"
  | "ScrollLock"
  | "NumLock"
  | "Insert"
  | "Delete"
  | "Home"
  | "End"
  | "PageUp"
  | "PageDown"
  | "ArrowUp"
  | "ArrowDown"
  | "ArrowLeft"
  | "ArrowRight"
  | "Space"

  /* ————————————————— Numpad ————————————————— */
  | "Numpad0"
  | "Numpad1"
  | "Numpad2"
  | "Numpad3"
  | "Numpad4"
  | "Numpad5"
  | "Numpad6"
  | "Numpad7"
  | "Numpad8"
  | "Numpad9"
  | "NumpadDecimal"
  | "NumpadAdd"
  | "NumpadSubtract"
  | "NumpadMultiply"
  | "NumpadDivide"
  | "NumpadEnter"
  | "NumpadEqual"
  | "NumpadComma"
  | "NumpadParenLeft"
  | "NumpadParenRight"

  /* ————————————————— Symbols / punctuation ————————————————— */
  | "Minus"
  | "Equal"
  | "BracketLeft"
  | "BracketRight"
  | "Backslash"
  | "Semicolon"
  | "Quote"
  | "Backquote"
  | "Comma"
  | "Period"
  | "Slash"
  | "IntlBackslash"
  | "IntlRo"
  | "IntlYen"

  /* ————————————————— International / IME ————————————————— */
  | "Lang1"
  | "Lang2"
  | "Lang3"
  | "Lang4"
  | "Lang5"
  | "Convert"
  | "NonConvert"
  | "KanaMode"
  | "HangulMode"
  | "Kana"
  | "KanjiMode"

  /* ————————————————— Media & others (optional but common) ————————————————— */
  | "MediaTrackNext"
  | "MediaTrackPrevious"
  | "MediaStop"
  | "MediaPlayPause"
  | "AudioVolumeMute"
  | "AudioVolumeUp"
  | "AudioVolumeDown";
